"""Add payment plan field

Revision ID: b345b3b3ec0c
Revises: f123456789
Create Date: 2025-09-24 15:11:55.314416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b345b3b3ec0c'
down_revision: Union[str, None] = 'f123456789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_id_key'), 'users', type_='unique')
    op.add_column('waitlist', sa.Column('payment_plan', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlist', 'payment_plan')
    op.create_unique_constraint(op.f('users_id_key'), 'users', ['id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
