"""add_item_id_to_user

Revision ID: d9c56fcfaa24
Revises: 551810a646d8
Create Date: 2025-08-31 13:06:36.490681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c56fcfaa24'
down_revision: Union[str, None] = '551810a646d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plaid_item_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plaid_item_id')
    # ### end Alembic commands ###
