"""Add onboarding fields to user model

Revision ID: e9f3d363b116
Revises: 92fb1f16f4be
Create Date: 2025-06-09 18:02:39.116246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f3d363b116'
down_revision: Union[str, None] = '92fb1f16f4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('onboarding_step', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('college_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('is_student', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('financial_goals', sa.Text(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'total_balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'salary_monthly',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'monthly_spending_goal',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'monthly_spending_goal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'salary_monthly',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'total_balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'financial_goals')
    op.drop_column('users', 'is_student')
    op.drop_column('users', 'college_name')
    op.drop_column('users', 'onboarding_step')
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
